spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firefly_whisper 
    username: root
    password: crey199854
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

allowed_origin: http://localhost:9100